### ISSUE TITLE
Центрируем Team при маленькой ширине страницы

### ISSUE THREAD

**Issue by GeorgeHub2018** [ilasa/flexbox_landingpage#1]
[http://i.piccy.info/i9/c0daeac6eeafa54a61d9a6118f1b6c67/1563199700/95684/1327945/sScreenshot_1.png](url)

**Comment by ilasa** [comment]
Done!
/*Центрируем Team при маленькой ширине страницы: убрали у div founder width:100%*/
.founder {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    text-align: center;
    text-transform: capitalize;
}

**Comment by GeorgeHub2018** [comment]
Проверил. Выполнено.
