### ISSUE TITLE
Избавляемся от пробела справа при большой ширине экрана

### ISSUE THREAD

**Issue by GeorgeHub2018** [ilasa/flexbox_landingpage#2]
[http://i.piccy.info/i9/782c542cbe34d4c64f015a626f497bf6/1563199754/126667/1327945/sScreenshot_2.jpg](url)

**Comment by ilasa** [comment]
Done!
Картинка без масштабирования: "Если используется картинка как фон, то ей ставится изначальный размер как на шаблоне дизайна (исходный размер) и выравнивается по центру".

.mission {
    flex-direction: column;
    justify-content: flex-end;
    align-items: center;
    background-image: url(img/main.png); /* картинка при ширине экрана 50% 
  - отображается только ее половина по горизонтали, при 100% полностью отображается*/
    background-size: cover;
    width: 1440px;
    height: 600px;
    background-repeat: no-repeat;
    background-attachment: scroll;
    color: #f7fdfe;
}

**Comment by GeorgeHub2018** [comment]
Картинку подвинула, но теперь у тебя в хедере Logo вылезает за ширину шаблона, проверь.

**Comment by ilasa** [comment]
Задала всем основным элементам необходимую ширину по макету, в моем браузере Chrome отображается корректно при большой ширине экрана, разве что background  у footer растягивается во всю ширину. При дальнейшей разработке отнесусь более внимательно.

**Comment by GeorgeHub2018** [comment]
Сделано
