### ISSUE TITLE
Приводим картинки в соответствие с размером и изображением

### ISSUE THREAD

**Issue by GeorgeHub2018** [ilasa/flexbox_landingpage#3]
[http://i.piccy.info/i9/fb08b8541fc159a9f1db5e133533857f/1563200379/3908/1327945/Bezymiannyi3.png](url)

**Comment by ilasa** [comment]
Done!
/* Привели картинки в соответствие с размером и изображением #3 */

.footer_icon {
    display: flex;
    justify-content: center;
    flex-direction: column;
    align-items: center;
    margin-left: 10px;
    border: 1px solid #d7dee4;
    border-radius: 100%;
    width: 40px;
    height: 40px;
}

**Comment by GeorgeHub2018** [comment]
Проверил. Выполнено.
