### ISSUE TITLE
Изучаем подключение шрифтов

### ISSUE THREAD

**Issue by GeorgeHub2018** [ilasa/flexbox_landingpage#4]
Проходимся по сайту и выставляем везде шрифты (вместе с размером) для текстов в соответствии с шаблоном.

Мануал по подключению шрифтов [http://site4business.net/css/kak-podklyuchit-shrift.html](url)

**Comment by ilasa** [comment]
Подключились ли шрифты?
Когда сайт открываешь, и выбираешь в инструментах разработчика текст, то можно увидеть шрифт который применен. 
Гит предлагает извлечь шрифты, не получилось отправить ссылки.

**Comment by ilasa** [comment]
Шрифты внешние подключены, также в head в html есть google шрифты, можно (на данный момент закомментированные).

**Comment by GeorgeHub2018** [comment]
Сделано.
