### ISSUE TITLE
Добавляем звездочки для Our Mission, как на макете

### ISSUE THREAD

**Issue by GeorgeHub2018** [ilasa/flexbox_landingpage#6]

**Comment by ilasa** [comment]
Done! 
.beforeafter {
    display: inline-block;
}

.beforeafter .headline:before {
    content: url(/img/star1.png);
   padding-right: 19px;
} 

.beforeafter .headline:after{
    content: url(/img/star1.png);
    padding-left: 19px;
}

**Comment by GeorgeHub2018** [comment]
Звездочек не видно.

**Comment by ilasa** [comment]
На моем сайте их видно в браузере.

**Comment by GeorgeHub2018** [comment]
Выполнено.
